### ISSUE TITLE
[OT] - Thank you

### ISSUE THREAD

**Issue by elcuervo** [luislavena/mysql-gem#29]
It was hard for me to pick one project to say thank you ^_^.

You are one of the invisible ones, the ones that give tremendous tools to the community and sadly deal with the jokes and consequences.

I just want to take time to say thank you for your hard work and for the countless hours you spent helping other. A bunch of us are aware that your time and passion is priceless so thank you for sharing it.

**Comment by luislavena** [comment]
Thank you @elcuervo
