### ISSUE TITLE
License

### ISSUE THREAD

**Issue by reiz** [luislavena/mysql-gem#30]
Under which license is this project? MIT? Apache-2.0? I need the info for [VersionEye](https://www.versioneye.com).

**Comment by luislavena** [comment]
Please look at the code, is Ruby's license.

https://github.com/luislavena/mysql-gem/blob/master/COPYING

Sorry for top posting. Sent from mobile.

**Comment by reiz** [comment]
@luislavena Thanks. Is this the upstream for the mysql gem on RubyGems? If yes, it would be nice to include the license information into the gemspec ;-)

**Comment by luislavena** [comment]
This gem is looking for a maintainer, no new release is scheduled.

If it had a maintainer perhaps a pull request could be accepted.
